server:
  port: 8764
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: '123456.'    
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    metadata-map.zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-east
    service-url:
      zone1: http://admin:123456.@localhost:8761/eureka/,http://admin:123456.@localhost:8762/eureka/
      zone2: http://admin:123456.@localhost:8763/eureka/,http://admin:123456.@localhost:8764/eureka/
    availability-zones:
      region-east: zone1,zone2
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false