server:
  port: 8763
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: '123456.' 
  rabbitmq:
    username: rabbit
    password: 123456
    host: localhost
    port: 5672
    virtual-host: /
    #手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none
    listener:
      simple:
        acknowledge-mode: manual          
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    metadata-map.zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-east
    service-url:
      zone1: http://admin:123456.@localhost:8761/eureka/,http://admin:123456.@localhost:8762/eureka/
      zone2: http://admin:123456.@localhost:8763/eureka/,http://admin:123456.@localhost:8764/eureka/
    availability-zones:
      region-east: zone1,zone2
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false
info.app.name: eureka-server
info.app.version: 1.0.0
info.app.test: test     
info.app.testadd: testadd       