server:
  port: 8762
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: '123456.'
  rabbitmq:
    username: rabbit
    password: 123456
    host: localhost
    port: 5672
    virtual-host: /
    #手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none
    listener:
      simple:
        acknowledge-mode: manual           
eureka:
  instance:
#    hostname: eureka-server
    hostname: localhost
    preferIpAddress: true
#    status-page-url-path: /actuator/info
#    health-check-url-path: /actuator/health    
#    metadata-map.zone: zone1  #设置实例所属的zone，失效要应该使用：eureka.client.availabilityZones.beijing=myzone # beijing是region
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true #首先使用相同区域的
    region: region-east #所在区域
    service-url:
      zone1: http://admin:123456.@localhost:8761/eureka/,http://admin:123456.@localhost:8762/eureka/
      zone2: http://admin:123456.@localhost:8763/eureka/,http://admin:123456.@localhost:8764/eureka/
    availability-zones:
      region-east: zone1,zone2
  server:
    waitTimeInMsWhenSyncEmpty: 0
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9 
#management.endpoints.web.base-path=/monitor 代表启用单独的url地址来监控 Spring Boot 应用，为了安全一般都启用独立的端口来访问后端的监控信息
management.endpoint.shutdown.enabled: true #启用接口关闭 Spring Boot
info.app.name: eureka-server
info.app.version: 1.0.0
info.app.test: test
  